### ISSUE TITLE
作者可以留个联系方式吗

### ISSUE THREAD

**Issue by fqnfqn** [staringlin/movie#1]

**Comment by staringlin** [comment]
可以的，微信号：smallstarly

**Comment by fqnfqn** [comment]
非常开心收到你的来信，当时是同学要找毕业设计项目，才联系的。现在我们毕业设计已经接近尾声了，就不打扰了，还是非常谢谢你。------------------ 原始邮件 ------------------
发件人: "staringlin"<notifications@github.com>
发送时间: 2020年3月27日(星期五) 下午4:31
收件人: "staringlin/movie"<movie@noreply.github.com>;
抄送: "fqnfqn"<1398086615@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [staringlin/movie] 作者可以留个联系方式吗 (#1)




 
可以的，微信号：smallstarly
 
&mdash;
